### ISSUE TITLE
PECL & Repo Packages

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/sandbox#2]
Hi @remicollet, please can you get involved in this for me ?

**Comment by remicollet** [comment]
Of course I can help.

Please start announcing the new ext (for feedback) on the pecl ML

I will prepare the package.xml ASAP (busy with RM process for now)

**Comment by remicollet** [comment]
and please give me access so I can commit the package.xml ;)

**Comment by krakjoe** [comment]
I've sent an invite for that ... would you mind sending an email to internals, that's not working for me ? Just put yourself down as lead in pecl is fine ...

**Comment by remicollet** [comment]
> I've sent an invite for that 

works

> would you mind sending an email to internals,

http://news.php.net/php.pecl.dev/15688

**Comment by remicollet** [comment]
See 6926a4ed7d9787a3ae84fbd6960f1ca56966754f and 6d47748cd995d00e8ce7935e2208ef94be07ea61

Will wait a few days, per pecl process for new package, and then will import it

**Comment by krakjoe** [comment]
excellent stuff, thanks Remi :)

**Comment by remicollet** [comment]
And the RPM spec file also ready
https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-sandbox.git/tree/

So the RPM will be available in sync with pecl release :)

Test build on Various distro, version, arch, PHP versions, everything looks good (build + test suite)

**Comment by krakjoe** [comment]
Thanks remi, really appreciate all the time you spend on this stuff for me, and for php ... <3

**Comment by krakjoe** [comment]
I've created develop/release branch structure ... just fyi ... I'll let you figure out versioning when it comes time to release, don't know what you want to do there ... 0.1.1 is pretty meaningless ...

**Comment by krakjoe** [comment]
This is ready to go when you are ... I'm done messing with it until reports roll in ;)

**Comment by remicollet** [comment]
Package registered
https://pecl.php.net/package/sandbox

Will start the release process now

**Comment by remicollet** [comment]
@krakjoe Are you able to run test on 32-bit ?

1 test is failing (erratic failure... 1 for 5 build)

```
TEST 23/27 [tests/023.phpt]
========DIFF========
007+  ** ERROR: process timed out **
========DONE========
FAIL bailed [tests/023.phpt] 

```

**Comment by remicollet** [comment]
Only 1 failure on ~15 build... can probably be ignored for a first release...

**Comment by remicollet** [comment]
0.1.1 is released

**Comment by remicollet** [comment]
>don't know what you want to do there ... 0.1.1 is pretty meaningless ...

well... not so bad for a first release, at least you can continue to play with API change ;)

I think you can update to 0.3 ...0.8 as you think we are close to "stable", and then 1.0 when you think it is time to promote to stable.

**Comment by krakjoe** [comment]
ack, thanks for that @remicollet ...

I'll look at that 32bit thing, I don't have a vm right now ... weekend ...

Cheers
Joe
