### ISSUE TITLE
7.4.0alpha1 compatibility

### ISSUE THREAD

**Issue by remicollet** [krakjoe/sandbox#4]
Please review 35c65aa151fab72617fb09cef3f3d902dc7edd5d

**Comment by krakjoe** [comment]
Looks correct, could you add 7.4snapshot to CI ?

**Comment by remicollet** [comment]
Running https://travis-ci.org/krakjoe/sandbox/builds/545281343

**Comment by krakjoe** [comment]
Look fine.

**Comment by krakjoe** [comment]
oh, and obviously, thanks :)

**Comment by remicollet** [comment]
@krakjoe do you want a release for 7.4.0alpha1 ?

**Comment by krakjoe** [comment]
Yes please @remicollet
